--------------------------------------------------------
--  DDL for Table SDREE_CONTROL_INDEMNIZACIONES
--------------------------------------------------------

  CREATE TABLE "TEST"."SDREE_CONTROL_INDEMNIZACIONES" 
   (	"ID_INDEMNIZACION" NUMBER(10,0), 
	"ID_EMPLEADO" NUMBER(10,0), 
	"FECHA_INICIO_LABORES" DATE, 
	"FECHA_FIN_LABORES" DATE, 
	"SALARIO_VIGENTE" NUMBER, 
	"VALOR_INDEMNIZACION" NUMBER, 
	"TIPO_RETIRO" CHAR(1 BYTE), 
	"MOTIVO_RETIRO" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
