REM INSERTING into TEST.SDREE_CONTACTOS_EMERGENCIA
SET DEFINE OFF;
Insert into TEST.SDREE_CONTACTOS_EMERGENCIA (ID_PERSONA,ID_CONTACTO,NOMBRES,APELLIDOS,DIRECCION,TELEFONO_1,TELEFONO_2,EMAIL_1,EMAIL_2,ESTADO_CONTACTO) values (21,21,'GWR WRYJSTR',null,null,null,null,null,null,1);
Insert into TEST.SDREE_CONTACTOS_EMERGENCIA (ID_PERSONA,ID_CONTACTO,NOMBRES,APELLIDOS,DIRECCION,TELEFONO_1,TELEFONO_2,EMAIL_1,EMAIL_2,ESTADO_CONTACTO) values (2,1,'Ana','Ponce',null,null,null,null,null,1);
Insert into TEST.SDREE_CONTACTOS_EMERGENCIA (ID_PERSONA,ID_CONTACTO,NOMBRES,APELLIDOS,DIRECCION,TELEFONO_1,TELEFONO_2,EMAIL_1,EMAIL_2,ESTADO_CONTACTO) values (2,41,'test','test',null,null,null,null,null,1);
