REM INSERTING into TEST.SDREE_EMP_AFP
SET DEFINE OFF;
Insert into TEST.SDREE_EMP_AFP (ID_AFP,NOMBRE_AFP,DIRECCION,TELEFONO,CORREO_ELECTRONICO) values (1,'AFP Crecer','San Salvador','2000-0000','afp_crecer@afpcrecer.com');
Insert into TEST.SDREE_EMP_AFP (ID_AFP,NOMBRE_AFP,DIRECCION,TELEFONO,CORREO_ELECTRONICO) values (21,'AFP Confía','La Libertad','2999-9999','confia@confia.com');
