REM INSERTING into TEST.SDREE_CONTROL_INDEMNIZACIONES
SET DEFINE OFF;
Insert into TEST.SDREE_CONTROL_INDEMNIZACIONES (ID_INDEMNIZACION,ID_EMPLEADO,FECHA_INICIO_LABORES,FECHA_FIN_LABORES,SALARIO_VIGENTE,VALOR_INDEMNIZACION,TIPO_RETIRO,MOTIVO_RETIRO) values (1,2,to_date('21/04/21','DD/MM/RR'),to_date('17/05/23','DD/MM/RR'),450,450,'1','test');
