--------------------------------------------------------
--  DDL for Table SDREE_PERSONAS
--------------------------------------------------------

  CREATE TABLE "TEST"."SDREE_PERSONAS" 
   (	"ID_PERSONA" NUMBER(10,0), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE), 
	"FECHA_NACIMIENTO" DATE, 
	"NUMERO_IDENTIFICACION" VARCHAR2(100 BYTE), 
	"NIT" VARCHAR2(100 BYTE), 
	"ISSS" VARCHAR2(100 BYTE), 
	"ID_AFP" VARCHAR2(100 BYTE), 
	"AFP" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"TELEFONO_1" VARCHAR2(20 BYTE), 
	"TELEFONO_2" VARCHAR2(20 BYTE), 
	"EMAIL_1" VARCHAR2(50 BYTE), 
	"EMAIL_2" VARCHAR2(50 BYTE), 
	"FECHA_CONTRATACION" DATE, 
	"TIPO_CONTRATACION" NUMBER, 
	"SALARIO" NUMBER(10,2), 
	"ID_DEPARTAMENTO" NUMBER(10,0), 
	"ESTADO_PERSONA" NUMBER, 
	"TIPO_PERSONA" NUMBER, 
	"ID_CARGO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
