REM INSERTING into TEST.SDREE_PERSONAS
SET DEFINE OFF;
Insert into TEST.SDREE_PERSONAS (ID_PERSONA,NOMBRES,APELLIDOS,FECHA_NACIMIENTO,NUMERO_IDENTIFICACION,NIT,ISSS,ID_AFP,AFP,DIRECCION,TELEFONO_1,TELEFONO_2,EMAIL_1,EMAIL_2,FECHA_CONTRATACION,TIPO_CONTRATACION,SALARIO,ID_DEPARTAMENTO,ESTADO_PERSONA,TIPO_PERSONA,ID_CARGO) values (41,'Jorge','Ponce',null,null,null,null,'21',null,null,null,null,null,null,null,3,null,61,1,1,1);
