REM INSERTING into TEST.SDREE_CARGOS
SET DEFINE OFF;
Insert into TEST.SDREE_CARGOS (ID_CARGO,DESCRIPCION_CARGO,ID_DEPARTAMENTO,ESTADO) values (1,'Gerente General',1,0);
Insert into TEST.SDREE_CARGOS (ID_CARGO,DESCRIPCION_CARGO,ID_DEPARTAMENTO,ESTADO) values (21,'Gerente Recursos Humanos',21,1);
