--------------------------------------------------------
--  DDL for Table SDREE_PLANILLA_SALARIO
--------------------------------------------------------

  CREATE TABLE "TEST"."SDREE_PLANILLA_SALARIO" 
   (	"ID_PLANILLA" NUMBER(10,0), 
	"ID_EMPLEADO" NUMBER(10,0), 
	"MES" NUMBER, 
	"YEAR" NUMBER, 
	"SALARIO_DEVENGADO" NUMBER(14,2), 
	"DIAS_LABORADOS" NUMBER, 
	"DIAS_NO_LABORADOS" NUMBER, 
	"SALARIO_DIARIO" NUMBER(14,2), 
	"ID_RANGO_SALARIAL" NUMBER, 
	"ISSS_PATRONO" NUMBER(14,2), 
	"AFP_PATRONO" NUMBER(14,2), 
	"ISSS_EMPLEADO" NUMBER(14,2), 
	"AFP_EMPLEADO" NUMBER(14,2), 
	"SUELDO_NETO_ISR" NUMBER(14,2), 
	"EXCESO" NUMBER(14,2), 
	"PORCENTAJE" NUMBER(14,2), 
	"CUOTA_A" NUMBER(14,2), 
	"CUOTA_FIJA" NUMBER(14,2), 
	"ISR" NUMBER(14,2), 
	"ANTICIPOS" NUMBER(14,2), 
	"LLEGADAS_TARDE" NUMBER(14,2), 
	"OTROS_DESCUENTOS" NUMBER(14,2), 
	"TOTAL_A_PAGAR" NUMBER(14,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
