--------------------------------------------------------
--  DDL for Table SDREE_CONTROL_CENTROS_COSTOS
--------------------------------------------------------

  CREATE TABLE "TEST"."SDREE_CONTROL_CENTROS_COSTOS" 
   (	"ID_REGISTRO" NUMBER(10,0), 
	"ID_DEPARTAMENTO" NUMBER(10,0), 
	"MES" CHAR(2 BYTE), 
	"YEAR" CHAR(4 BYTE), 
	"VALOR_COSTO" NUMBER(14,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
