REM INSERTING into TEST.SDREE_RETENCIONES_ISR
SET DEFINE OFF;
Insert into TEST.SDREE_RETENCIONES_ISR (ID_RETENCION,PERIODICIDAD,DESCRIPCION,RANGO_DESDE,RANGO_HASTA,PORCENTAJE_EXCESO,VALOR_EXCESO,CUOTA_FIJA,ESTADO) values (1,' MENSUAL','TRAMO 1',0.01,472,0,0,0,1);
Insert into TEST.SDREE_RETENCIONES_ISR (ID_RETENCION,PERIODICIDAD,DESCRIPCION,RANGO_DESDE,RANGO_HASTA,PORCENTAJE_EXCESO,VALOR_EXCESO,CUOTA_FIJA,ESTADO) values (2,' MENSUAL','TRAMO 2',472.01,895.24,10,472,17.67,1);
Insert into TEST.SDREE_RETENCIONES_ISR (ID_RETENCION,PERIODICIDAD,DESCRIPCION,RANGO_DESDE,RANGO_HASTA,PORCENTAJE_EXCESO,VALOR_EXCESO,CUOTA_FIJA,ESTADO) values (3,' MENSUAL','TRAMO 3',895.25,2038.1,20,895.24,60,1);
Insert into TEST.SDREE_RETENCIONES_ISR (ID_RETENCION,PERIODICIDAD,DESCRIPCION,RANGO_DESDE,RANGO_HASTA,PORCENTAJE_EXCESO,VALOR_EXCESO,CUOTA_FIJA,ESTADO) values (4,' MENSUAL','TRAMO 4',2038.11,null,30,2038.1,288.57,1);
