REM INSERTING into TEST.SDREE_CONTROL_INCAPACIDADES
SET DEFINE OFF;
Insert into TEST.SDREE_CONTROL_INCAPACIDADES (ID_INCAPACIDAD,ID_EMPLEADO,FECHA_INICIO,FECHA_FIN,TIPO_INCAPACIDAD,MOTIVO) values (1,2,to_date('18/05/23','DD/MM/RR'),to_date('31/05/23','DD/MM/RR'),null,'Test');
