REM INSERTING into TEST.SDREE_CONTROL_AUSENCIAS
SET DEFINE OFF;
Insert into TEST.SDREE_CONTROL_AUSENCIAS (ID_AUSENCIA,ID_EMPLEADO,FECHA_INICIO,FECHA_FIN,TIPO_AUSENCIA,MOTIVO) values (1,1,to_date('18/05/23','DD/MM/RR'),to_date('19/05/23','DD/MM/RR'),'1','Pruebas');
