REM INSERTING into TEST.SDREE_PLANILLA_SALARIO_ENC
SET DEFINE OFF;
Insert into TEST.SDREE_PLANILLA_SALARIO_ENC (ID_PLANILLA,MES,YEAR) values (36,1,2023);
Insert into TEST.SDREE_PLANILLA_SALARIO_ENC (ID_PLANILLA,MES,YEAR) values (37,2,2023);
Insert into TEST.SDREE_PLANILLA_SALARIO_ENC (ID_PLANILLA,MES,YEAR) values (41,3,2023);
