--------------------------------------------------------
--  DDL for Table SDREE_CONTACTOS_EMERGENCIA
--------------------------------------------------------

  CREATE TABLE "TEST"."SDREE_CONTACTOS_EMERGENCIA" 
   (	"ID_PERSONA" NUMBER(10,0), 
	"ID_CONTACTO" NUMBER(10,0), 
	"NOMBRES" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"TELEFONO_1" VARCHAR2(20 BYTE), 
	"TELEFONO_2" VARCHAR2(20 BYTE), 
	"EMAIL_1" VARCHAR2(50 BYTE), 
	"EMAIL_2" VARCHAR2(50 BYTE), 
	"ESTADO_CONTACTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
