--------------------------------------------------------
--  Ref Constraints for Table SDREE_PERSONAS
--------------------------------------------------------

  ALTER TABLE "TEST"."SDREE_PERSONAS" ADD CONSTRAINT "FK_ID_CARGO_PERSO" FOREIGN KEY ("ID_CARGO")
	  REFERENCES "TEST"."SDREE_CARGOS" ("ID_CARGO") ENABLE;
  ALTER TABLE "TEST"."SDREE_PERSONAS" ADD CONSTRAINT "FK_ID_CONTRATACION_PERSO" FOREIGN KEY ("TIPO_CONTRATACION")
	  REFERENCES "TEST"."SDREE_TIPOS_CONTRATACIONES" ("ID_CONTRATACION") ENABLE;
  ALTER TABLE "TEST"."SDREE_PERSONAS" ADD CONSTRAINT "FK_ID_DEPARTAMENTO_PERSO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "TEST"."SDREE_DEPARTAMENTOS" ("ID_DEPARTAMENTO") ENABLE;
  ALTER TABLE "TEST"."SDREE_PERSONAS" ADD CONSTRAINT "FK_ID_TIPO_PERSONA" FOREIGN KEY ("TIPO_PERSONA")
	  REFERENCES "TEST"."SDREE_TIPOS_PERSONAS" ("ID_TIPO_PERSONA") ENABLE;
