REM INSERTING into TEST.SDREE_TIPOS_CONTRATACIONES
SET DEFINE OFF;
Insert into TEST.SDREE_TIPOS_CONTRATACIONES (ID_CONTRATACION,DESCRIPCION_CONTRATACION,ESTADO) values (1,'Servicios Profesionales',0);
Insert into TEST.SDREE_TIPOS_CONTRATACIONES (ID_CONTRATACION,DESCRIPCION_CONTRATACION,ESTADO) values (2,'Contrato Laboral Tiempo Indefinido',1);
Insert into TEST.SDREE_TIPOS_CONTRATACIONES (ID_CONTRATACION,DESCRIPCION_CONTRATACION,ESTADO) values (3,'Contrato Laboral Tiempo Definido',1);
Insert into TEST.SDREE_TIPOS_CONTRATACIONES (ID_CONTRATACION,DESCRIPCION_CONTRATACION,ESTADO) values (21,'egrgwerwert',0);
