--------------------------------------------------------
--  DDL for Table SDREE_PLANILLA_SALARIO_ENC
--------------------------------------------------------

  CREATE TABLE "TEST"."SDREE_PLANILLA_SALARIO_ENC" 
   (	"ID_PLANILLA" NUMBER(10,0), 
	"MES" NUMBER, 
	"YEAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
