REM INSERTING into TEST.SDREE_CONTROL_CENTROS_COSTOS
SET DEFINE OFF;
Insert into TEST.SDREE_CONTROL_CENTROS_COSTOS (ID_REGISTRO,ID_DEPARTAMENTO,MES,YEAR,VALOR_COSTO) values (2,1,'6 ','2023',3000);
Insert into TEST.SDREE_CONTROL_CENTROS_COSTOS (ID_REGISTRO,ID_DEPARTAMENTO,MES,YEAR,VALOR_COSTO) values (3,61,'1 ','2023',3500);
Insert into TEST.SDREE_CONTROL_CENTROS_COSTOS (ID_REGISTRO,ID_DEPARTAMENTO,MES,YEAR,VALOR_COSTO) values (1,1,'1 ','2023',2630.2);
