REM INSERTING into TEST.SDREE_DEPARTAMENTOS
SET DEFINE OFF;
Insert into TEST.SDREE_DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO,DESCRIPCION_DEPARTAMENTO,ESTADO) values (61,'Departamento de Contabilidad','de ContabilidDepartamento ad',0);
Insert into TEST.SDREE_DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO,DESCRIPCION_DEPARTAMENTO,ESTADO) values (1,'Gerencia General','Gerencia General',1);
Insert into TEST.SDREE_DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO,DESCRIPCION_DEPARTAMENTO,ESTADO) values (21,'Gerencia Recursos Humanos','Gerencia Recursos Humanos',1);
Insert into TEST.SDREE_DEPARTAMENTOS (ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO,DESCRIPCION_DEPARTAMENTO,ESTADO) values (41,'test','test',1);
