REM INSERTING into TEST.SDREE_BENEFICIOS_EMPLEADOS
SET DEFINE OFF;
Insert into TEST.SDREE_BENEFICIOS_EMPLEADOS (ID_BENEFICIO,DESCRIPCION_BENEFICIO,ESTADO) values (1,'Canasta Mensual $25.00',1);
Insert into TEST.SDREE_BENEFICIOS_EMPLEADOS (ID_BENEFICIO,DESCRIPCION_BENEFICIO,ESTADO) values (2,'Bono semestral',1);
Insert into TEST.SDREE_BENEFICIOS_EMPLEADOS (ID_BENEFICIO,DESCRIPCION_BENEFICIO,ESTADO) values (3,'Salario 14',1);
Insert into TEST.SDREE_BENEFICIOS_EMPLEADOS (ID_BENEFICIO,DESCRIPCION_BENEFICIO,ESTADO) values (4,'Línea Celular',1);
Insert into TEST.SDREE_BENEFICIOS_EMPLEADOS (ID_BENEFICIO,DESCRIPCION_BENEFICIO,ESTADO) values (21,'Prueba',1);
