--------------------------------------------------------
--  DDL for Table SDREE_RETENCIONES_ISR
--------------------------------------------------------

  CREATE TABLE "TEST"."SDREE_RETENCIONES_ISR" 
   (	"ID_RETENCION" NUMBER(10,0), 
	"PERIODICIDAD" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"RANGO_DESDE" NUMBER(14,2), 
	"RANGO_HASTA" NUMBER(14,2), 
	"PORCENTAJE_EXCESO" NUMBER(14,2), 
	"VALOR_EXCESO" NUMBER(14,2), 
	"CUOTA_FIJA" NUMBER(14,2), 
	"ESTADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
