REM INSERTING into TEST.SDREE_TIPOS_PERSONAS
SET DEFINE OFF;
Insert into TEST.SDREE_TIPOS_PERSONAS (ID_TIPO_PERSONA,DESCRIPCION_PERSONA,ESTADO) values (1,'Empleado Permanente',1);
Insert into TEST.SDREE_TIPOS_PERSONAS (ID_TIPO_PERSONA,DESCRIPCION_PERSONA,ESTADO) values (2,'Empleado Temporal',1);
Insert into TEST.SDREE_TIPOS_PERSONAS (ID_TIPO_PERSONA,DESCRIPCION_PERSONA,ESTADO) values (3,'Profesional Independiente',1);
