--------------------------------------------------------
--  DDL for Index SYS_C007704
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C007704" ON "TEST"."SDREE_CONTROL_CENTROS_COSTOS" ("ID_REGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
