--------------------------------------------------------
--  DDL for Index SYS_C007616
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."SYS_C007616" ON "TEST"."SDREE_RETENCIONES_ISR" ("ID_RETENCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
